//higan_accuracy --> perfecto para SGB

var DATABASE_BY_EXTENSION={
	'a26':'Atari - 2600',
	'a52':'Atari - 5200',
	'a78':'Atari - 7800',
	'j64':'Atari - Jaguar',
	'lnx':'Atari - Lynx',
	'ws':'Bandai - WonderSwan',
	'wsc':'Bandai - WonderSwan Color',
	'col':'Coleco - ColecoVision',
	'vec':'GCE - Vectrex',
	'pce':'NEC - PC Engine - TurboGrafx 16',
	'sgx':'NEC - PC Engine SuperGrafx',
	'fds':'Nintendo - Family Computer Disk System',
	'gba':'Nintendo - Game Boy Advance',
	'gbc':'Nintendo - Game Boy Color',
	'gb':'Nintendo - Game Boy',
	'3ds':'Nintendo - Nintendo 3DS',
	'v64':'Nintendo - Nintendo 64',
	'z64':'Nintendo - Nintendo 64',
	'ndd':'Nintendo - Nintendo 64DD',
	'nds':'Nintendo - Nintendo DS',
	'nes':'Nintendo - Nintendo Entertainment System',
	'min':'Nintendo - Pokemon Mini',
	'bs':'Nintendo - Satellaview',
	'sfc':'Nintendo - Super Nintendo Entertainment System',
	'vb':'Nintendo - Virtual Boy',
	'wbfs':'Nintendo - Wii',
	'scummvm':'ScummVM',
	'32x':'Sega - 32X',
	'gdi':'Sega - Dreamcast',
	'gg':'Sega - Game Gear',
	'sms':'Sega - Master System - Mark III',
	'md':'Sega - Mega Drive - Genesis',
	'sg':'Sega - SG-1000',
	'ngp':'SNK - Neo Geo Pocket',
	'ngc':'SNK - Neo Geo Pocket Color'
};
var REGEX_KNOWN_EXTENSIONS=new RegExp('\\.('+Object.keys(DATABASE_BY_EXTENSION).join('|')+')$', 'i');
var knownDatabases=[
	'Amstrad - CPC',
	'Atari - 2600',
	'Atari - 5200',
	'Atari - 7800',
	'Atari - Jaguar',
	'Atari - Lynx',
	'Atari - ST',
	'Bandai - WonderSwan',
	'Bandai - WonderSwan Color',
	'Coleco - ColecoVision',
	'Commodore - 64',
	'Commodore - Amiga',
	'Commodore - Plus-4',
	'DOOM',
	'DOS',
	'FBNeo - Arcade Games',
	'GCE - Vectrex',
	'MAME 2000',
	'MAME 2003',
	'MAME 2003-Plus',
	'MAME 2010',
	'MAME',
	'Microsoft - MSX',
	'Microsoft - MSX2',
	'NEC - PC Engine - TurboGrafx 16',
	'NEC - PC Engine CD - TurboGrafx-CD',
	'NEC - PC Engine SuperGrafx',
	'NEC - PC-98',
	'NEC - PC-FX',
	'Nintendo - Family Computer Disk System',
	'Nintendo - Game Boy Advance',
	'Nintendo - Game Boy Color',
	'Nintendo - Game Boy',
	'Nintendo - GameCube',
	'Nintendo - Nintendo 3DS',
	'Nintendo - Nintendo 64',
	'Nintendo - Nintendo 64DD',
	'Nintendo - Nintendo DS',
	'Nintendo - Nintendo DSi',
	'Nintendo - Nintendo Entertainment System',
	'Nintendo - Pokemon Mini',
	'Nintendo - Satellaview',
	'Nintendo - Super Nintendo Entertainment System',
	'Nintendo - Virtual Boy',
	'Nintendo - Wii',
	'ScummVM',
	'Sega - 32X',
	'Sega - Dreamcast',
	'Sega - Game Gear',
	'Sega - Master System - Mark III',
	'Sega - Mega Drive - Genesis',
	'Sega - Mega-CD - Sega CD',
	'Sega - PICO',
	'Sega - Saturn',
	'Sega - SG-1000',
	'Sharp - X68000',
	'Sinclair - ZX 81',
	'Sinclair - ZX Spectrum',
	'Sinclair - ZX Spectrum +3',
	'SNK - Neo Geo CD',
	'SNK - Neo Geo Pocket',
	'SNK - Neo Geo Pocket Color',
	'Sony - PlayStation',
	'Sony - PlayStation 2',
	'Sony - PlayStation Portable',
	'The 3DO Company - 3DO'
];

var FETCHABLE_DATABASES=[
'Atari - 2600',
'Atari - 5200',
'Atari - 7800',
'Atari - Jaguar',
'Atari - Lynx',
'Atari - ST',
'Bandai - WonderSwan Color',
'Bandai - WonderSwan',
'Coleco - ColecoVision',
'Commodore - Amiga',
'FBNeo - Arcade Games',
'MAME 2000',
'MAME 2003-Plus',
'MAME 2003',
'MAME 2010',
'MAME',
'Microsoft - MSX',
'Microsoft - MSX2',
'NEC - PC Engine - TurboGrafx 16',
'NEC - PC Engine CD - TurboGrafx-CD',
'NEC - PC Engine SuperGrafx',
'Nintendo - Family Computer Disk System',
'Nintendo - Game Boy Advance',
'Nintendo - Game Boy Color',
'Nintendo - Game Boy',
'Nintendo - GameCube',
'Nintendo - Nintendo 3DS (Digital)',
'Nintendo - Nintendo 3DS',
'Nintendo - Nintendo 64',
'Nintendo - Nintendo 64DD',
'Nintendo - Nintendo DS',
'Nintendo - Nintendo Entertainment System',
'Nintendo - Pokemon Mini',
'Nintendo - Satellaview',
'Nintendo - Super Nintendo Entertainment System',
'Nintendo - Virtual Boy',
'Nintendo - Wii (Digital)',
'Nintendo - Wii',
'Sega - 32X',
'Sega - Dreamcast',
'Sega - Game Gear',
'Sega - Master System - Mark III',
'Sega - Mega Drive - Genesis',
'Sega - Mega-CD - Sega CD',
'Sega - Saturn',
'SNK - Neo Geo CD',
'SNK - Neo Geo Pocket Color',
'SNK - Neo Geo Pocket',
'Sony - PlayStation'
];

var RECOMMENDED_CORES_BY_DATABASE={
	'Amstrad - CPC':'cap32_libretro',
	'Atari - 2600':'stella_libretro',
	'Atari - 8-bit computers':'atari800_libretro',
	'Atari - 5200':'a5200_libretro',
	'Atari - 7800':'prosystem_libretro',
	'Atari - Jaguar':'virtualjaguar_libretro',
	'Atari - Lynx':'mednafen_lynx_libretro',
	'Atari - ST':'hatari_libretro',
	'Atari - ST/STE/TT/Falcon':'hatari_libretro',
	'Bandai - WonderSwan':'mednafen_wswan_libretro',
	'Bandai - WonderSwan Color':'mednafen_wswan_libretro',
	'Coleco - ColecoVision':'bluemsx_libretro',
	'Commodore - 64':'vice_x64_libretro',
	'Commodore - 128':'vice_x128_libretro',
	'Commodore - Amiga':'puae_libretro',
	'DOS':'dosbox_pure_libretro',
	'FBNeo - Arcade Games':'fbneo_libretro',
	'GCE - Vectrex':'vecx_libretro',
	'Handheld Electronic Game':'gw_libretro',
	'Magnavox - Odyssey2':'o2em_libretro',
	'MAME 2000':'mame2000_libretro',
	'MAME 2003':'mame2003_libretro',
	'MAME 2003-Plus':'mame2003_plus_libretro',
	'MAME 2010':'mame2010_libretro',
	'MAME':'mame_libretro',
	'Mattel - Intellivision':'freeintv_libretro',
	'Microsoft - MSX':'fmsx_libretro',
	'Microsoft - MSX2':'fmsx_libretro',
	'NEC - PC Engine - TurboGrafx 16':'mednafen_pce_fast_libretro',
	'NEC - PC Engine CD - TurboGrafx-CD':'mednafen_pce_fast_libretro',
	'NEC - PC Engine SuperGrafx':'mednafen_supergrafx_libretro',
	'NEC - PC-FX':'mednafen_pcfx_libretro',
	'NEC - PC-98':'np2kai_libretro',
	'NEC - PC-8000/PC-8800':'quasi88_libretro',
	'Nintendo - Game Boy':'gambatte_libretro',
	'Nintendo - Game Boy Color':'gambatte_libretro',
	'Nintendo - Game Boy Advance':'mgba_libretro',
	'Nintendo - e-Reader':'mgba_libretro',
	'Nintendo - Pokemon Mini':'pokemini_libretro',
	'Nintendo - Nintendo DS':'desmume_libretro',
	'Nintendo - Nintendo DS (Download Play)':'desmume_libretro',
	'Nintendo - Nintendo DS (Download Play) (BETA)':'desmume_libretro',
	'Nintendo - Nintendo DSi':'melonds_libretro',
	'Nintendo - Nintendo DSi Decrypted':'melonds_libretro',
	'Nintendo - Nintendo 3DS':'citra_libretro',
	'Nintendo - Nintendo 3DS (Digital)':'citra_libretro',
	'Nintendo - Nintendo Entertainment System':'bnes_libretro',
	'Nintendo - Family Computer Disk System':'fceumm_libretro',
	'Nintendo - Super Nintendo Entertainment System':'snes9x_libretro',
	'Nintendo - Virtual Boy':'mednafen_vb_libretro',
	'Nintendo - Satellaview':'snes9x_libretro',
	'Nintendo - Sufami Turbo':'snes9x_libretro',
	'Nintendo - Nintendo 64':'mupen64plus_next_libretro',
	'Nintendo - Nintendo 64DD':'mupen64plus_next_libretro',
	'Nintendo - GameCube':'dolphin_libretro',
	'Nintendo - Wii':'dolphin_libretro',
	'Nintendo - Wii (Digital)':'dolphin_libretro',
	'ScummVM':'scummvm_libretro',
	'Sega - 32X':'picodrive_libretro',
	'Sega - Dreamcast':'flycast_libretro',
	'Sega - Game Gear':'genesis_plus_gx_libretro',
	'Sega - Master System - Mark III':'genesis_plus_gx_libretro',
	'Sega - Mega Drive - Genesis':'genesis_plus_gx_libretro',
	'Sega - Mega-CD - Sega CD':'genesis_plus_gx_libretro',
	'Sega - PICO':'genesis_plus_gx_libretro',
	'Sega - Saturn':'mednafen_saturn_libretro',
	'Sega - SG-1000':'bluemsx_libretro',
	'Sharp - X68000':'px68k_libretro',
	'Sinclair - ZX 81':'81_libretro',
	'Sinclair - ZX Spectrum':'fuse_libretro',
	'Sinclair - ZX Spectrum +3':'fuse_libretro',
	'SNK - Neo Geo CD':'neocd_libretro',
	'SNK - Neo Geo Pocket':'mednafen_ngp_libretro',
	'SNK - Neo Geo Pocket Color':'mednafen_ngp_libretro',
	'Sony - PlayStation':'mednafen_psx_libretro',
	'Sony - PlayStation 2':'play_libretro',
	'Sony - PlayStation Portable':'ppsspp_libretro',
	'Sony - PlayStation Portable (PSN)':'ppsspp_libretro',
	'The 3DO Company - 3DO':'opera_libretro'
};

//this list includes prettified core names, it will grow temporarily as the user loads playlists
var knownCoreNames={
	// Amstrad
	'cap32_libretro':'Amstrad - CPC (Caprice32)',
	'crocods_libretro':'Amstrad - CPC/GX4000 (CrocoDS)',

	//Arcade
	'fbalpha2012_cps1_libretro':'Arcade (FB Alpha 2012 CPS-1)',
	'fbalpha2012_cps2_libretro':'Arcade (FB Alpha 2012 CPS-2)',
	'fbalpha2012_cps3_libretro':'Arcade (FB Alpha 2012 CPS-3)',
	'fbalpha2012_neogeo_libretro':'Arcade (FB Alpha 2012 Neo Geo)',
	'fbalpha2012_libretro':'Arcade (FB Alpha 2012)',
	'fbalpha_libretro':'Arcade (FinalBurn Alpha)',
	'fbneo_libretro':'Arcade (FinalBurn Neo)',
	'mame2000_libretro':'Arcade (MAME 2000)', //v0.37b5
	'mame2003_libretro':'Arcade (MAME 2003)', //v0.78
	'mame2003_midway_libretro':'Arcade (MAME 2003 Midway)',
	'mame2003_plus_libretro':'Arcade (MAME 2003-Plus)',
	'mame2010_libretro':'Arcade (MAME 2010)', //v0.139
	'mame_libretro':'Arcade (MAME - Current)',

	//Atari
	'stella_libretro':'Atari - 2600 (Stella)',
	'stella2014_libretro':'Atari - 2600 (Stella 2014)',
	'a5200_libretro':'Atari - 5200 (a5200)',
	'atari800_libretro':'Atari - 5200 (Atari800)',
	'prosystem_libretro':'Atari - 7800 (ProSystem)',
	'virtualjaguar_libretro':'Atari - Jaguar (Virtual Jaguar)',
	'mednafen_lynx_libretro':'Atari - Lynx (Beetle Lynx)',
	'handy_libretro':'Atari - Lynx (Handy)',
	'hatari_libretro':'Atari - ST/STE/TT/Falcon (Hatari)',

	//Bandai
	'mednafen_wswan_libretro':'Bandai - WonderSwan/Color (Beetle Cygne)',
	
	//Coleco
	'gearcoleco_libretro':'Coleco - ColecoVision (Gearcoleco)',

	//Commodore
	'puae_libretro':'Commodore - Amiga (PUAE)',
	'uae4arm_libretro':'Commodore - Amiga (UAE4ARM)',
	'vice_x128_libretro':'Commodore - C128 (VICE x128)',
	'frodo_libretro':'Commodore - C64 (Frodo)',
	'vice_x64_libretro':'Commodore - C64 (VICE x64, fast)',
	'vice_x64sc_libretro':'Commodore - C64 (VICE x64, accurate)',
	'vice_xcbm2_libretro':'Commodore - CBM-II 6x0/7x0 (VICE xcbm2)',
	'vice_xpet_libretro':'Commodore - PET (VICE xpet)',
	'vice_xplus4_libretro':'Commodore - PLUS/4 (VICE xplus4)',
	'vice_xvic_libretro':'Commodore - VIC-20 (VICE xvic)',
	
	//DOS
	'dosbox_core_libretro':'DOS (DOSBox-core)',
	'dosbox_pure_libretro':'DOS (DOSBox-Pure)',
	'dosbox_svn_libretro':'DOS (DOSBox-SVN)',
	
	//MSX
	'fmsx_libretro':'Microsoft - MSX (fMSX)',
	'bluemsx_libretro':'MSX/SVI/ColecoVision/SG-1000 (blueMSX)',
	
	//NEC
	'mednafen_pce_libretro':'NEC - PC Engine / SuperGrafx / CD (Beetle PCE)',
	'mednafen_pce_fast_libretro':'NEC - PC Engine / CD (Beetle PCE FAST)',
	'mednafen_supergrafx_libretro':'NEC - PC Engine SuperGrafx (Beetle SuperGrafx)',
	'quasi88_libretro':'NEC - PC-8000 / PC-8800 series (QUASI88)',
	'nekop2_libretro':'NEC - PC-98 (Neko Project II)',
	'np2kai_libretro':'NEC - PC-98 (Neko Project II Kai)',
	'mednafen_pcfx_libretro':'NEC - PC-FX (Beetle PC-FX)',

	//Nintendo
	'citra_libretro':'Nintendo - 3DS (Citra)',
	'citra2018_libretro':'Nintendo - 3DS (Citra 2018)',
	'citra_canary_libretro':'Nintendo - 3DS (Citra Canary/Experimental)',
	'desmume_libretro':'Nintendo - DS (DeSmuME)',
	'desmume2015_libretro':'Nintendo - DS (DeSmuME 2015)',
	'melonds_libretro':'Nintendo - DS (melonDS)',
	'gambatte_libretro':'Nintendo - Game Boy / Color (Gambatte)',
	'gearboy_libretro':'Nintendo - Game Boy / Color (Gearboy)',
	'sameboy_libretro':'Nintendo - Game Boy / Color (SameBoy)',
	'tgbdual_libretro':'Nintendo - Game Boy / Color (TGB Dual)',
	'gpsp_libretro':'Nintendo - Game Boy Advance (gpSP)',
	'mgba_libretro':'Nintendo - Game Boy Advance (mGBA)',
	'vba_next_libretro':'Nintendo - Game Boy Advance (VBA Next)',
	'vbam_libretro':'Nintendo - Game Boy Advance (VBA-M)',
	'dolphin_libretro':'Nintendo - GameCube / Wii (Dolphin)',
	'ishiiruka_libretro':'Nintendo - GameCube / Wii (Ishiiruka)',
	'fceumm_libretro':'Nintendo - NES / Famicom (FCEUmm)',
	'mesen_libretro':'Nintendo - NES / Famicom (Mesen)',
	'nestopia_libretro':'Nintendo - NES / Famicom (Nestopia UE)',
	'quicknes_libretro':'Nintendo - NES / Famicom (QuickNES)',
	'mupen64plus_next_libretro':'Nintendo - Nintendo 64 (Mupen64Plus-Next)',
	'mupen64plus_next_gles3_libretro':'Nintendo - Nintendo 64 (Mupen64Plus-Next GLES3)',
	'parallel_n64_libretro':'Nintendo - Nintendo 64 (ParaLLel N64)',
	'pokemini_libretro':'Nintendo - Pokemon Mini (PokeMini)',
	'bsnes2014_accuracy_libretro':'Nintendo - SNES / SFC (bsnes 2014 Accuracy)',
	'bsnes2014_balanced_libretro':'Nintendo - SNES / SFC (bsnes 2014 Balanced)',
	'bsnes2014_performance_libretro':'Nintendo - SNES / SFC (bsnes 2014 Performance)',
	'bsnes_libretro':'Nintendo - SNES / SFC (bsnes)',
	'bsnes_accuracy_libretro':'Nintendo - SNES / SFC (bsnes Accuracy)',
	'bsnes_balanced_libretro':'Nintendo - SNES / SFC (bsnes Balanced)',
	'bsnes_performance_libretro':'Nintendo - SNES / SFC (bsnes Performance)',
	'bsnes_hd_beta_libretro':'Nintendo - SNES / SFC (bsnes-hd beta)',
	'bsnes_mercury_accuracy_libretro':'Nintendo - SNES / SFC (bsnes-mercury Accuracy)',
	'bsnes_mercury_balanced_libretro':'Nintendo - SNES / SFC (bsnes-mercury Balanced)',
	'bsnes_mercury_performance_libretro':'Nintendo - SNES / SFC (bsnes-mercury Performance)',
	'snes9x_libretro':'Nintendo - SNES / SFC (Snes9x - Current)',
	'snes9x2002_libretro':'Nintendo - SNES / SFC (Snes9x 2002)',
	'snes9x2005_libretro':'Nintendo - SNES / SFC (Snes9x 2005)',
	'snes9x2005_plus_libretro':'Nintendo - SNES / SFC (Snes9x 2005 Plus)',
	'snes9x2010_libretro':'Nintendo - SNES / SFC (Snes9x 2010)',
	'mesen-s_libretro':'Nintendo - SNES / SFC / Game Boy / Color (Mesen-S)',
	'mednafen_vb_libretro':'Nintendo - Virtual Boy (Beetle VB)',

	//Sega
	'flycast_libretro':'Sega - Dreamcast/NAOMI (Flycast)',
	'blastem_libretro':'Sega - Mega Drive - Genesis (BlastEm)',
	'smsplus_libretro':'Sega - MS/GG (SMS Plus GX)',
	'genesis_plus_gx_libretro':'Sega - MS/GG/MD/CD (Genesis Plus GX)',
	'genesis_plus_gx_wide_libretro':'Sega - MS/GG/MD/CD (Genesis Plus GX (Widescreen Mod))',
	'picodrive_libretro':'Sega - MS/GG/MD/CD/32x (Picodrive)',
	'gearsystem_libretro':'Sega - MS/GG/SG-1000 (Gearsystem)',
	'mednafen_saturn_libretro':'Sega - Saturn (Beetle Saturn)',
	'yabanshiro_libretro':'Sega - Saturn (YabaSanshiro)',
	'yabause_libretro':'Sega - Saturn (Yabause)',
	'kronos_libretro':'Sega - Saturn/ST-V (Kronos)',

	//Sharp
	'px68k_libretro':'Sharp - X68000 (PX68k)',
	'x1_libretro':'Sharp X1 (X Millenium)',
	
	//Sinclair
	'81_libretro':'Sinclair - ZX 81 (EightyOne)',
	'fuse_libretro':'Sinclair - ZX Spectrum (Fuse)',

	//SNK
	'neocd_libretro':'SNK - Neo Geo CD (Neo CD)',
	'mednafen_ngp_libretro':'SNK - Neo Geo Pocket / Color (Beetle NeoPop)',
	'race_libretro':'SNK - Neo Geo Pocket / Color (RACE)',

	//Sony
	'mednafen_psx_libretro':'Sony - PlayStation (Beetle PSX)',
	'mednafen_psx_hw_libretro':'Sony - PlayStation (Beetle PSX HW)',
	'pcsx_rearmed_libretro':'Sony - PlayStation (PCSX ReARMed)',
	'swanstation_libretro':'Sony - PlayStation (SwanStation)',
	'pcsx2_libretro':'Sony - PlayStation 2 (PCSX2)',
	'play_libretro':'Sony - PlayStation 2 (Play!)',
	'ppsspp_libretro':'Sony - PlayStation Portable (PPSSPP)',
	
	//3DO
	'opera_libretro':'The 3DO Company - 4DO (Opera)',

	//Other
	'nxengine_libretro':'Cave Story (NXEngine)',
	'jaxe_libretro':'CHIP-8/S-CHIP/XO-CHIP (JAXE)',
	'prboom_libretro':'Doom (PrBoom)',
	'boom3_libretro':'Doom 3 (boom3)',
	'boom3_xp_libretro':'Doom 3: Resurrection of Evil (boom 3 xp)',
	'reminiscence_libretro':'Flashback (REminiscence)',
	'jumpnbump_libretro':'Jump \'n Bump',
	'gme_libretro':'Game Music Emu',
	'vecx_libretro':'GCE - Vectrex (vecx)',
	'gw_libretro':'Handheld Electronic (GW)',
	'squirreljme_libretro':'Java ME (SquirrelJME)',
	'o2em_libretro':'Magnavox - Odyssey2 / Phillips Videopac+ (O2EM)',
	'freeintv_libretro':'Mattel - Intellivision (FreeIntv)',
	'retro8_libretro':'PICO-8 (Retro8)',
	
	'tyrquake_libretro':'Quake (TyrQuake)',
	'vitaquake2_libretro':'Quake II (vitaQuake 2)',
	'vitaquake3_libretro':'Quake III (vitaQuake 3)',
	'xrick_libretro':'Rick Dangerous (XRick)',
	'easyrpg_libretro':'RPG Maker 2000/2003 (EasyRPG)',
	'scummvm_libretro':'ScummVM'
};